### ISSUE TITLE
March: Put operating systems on Raspberry Pis

### ISSUE THREAD

**Issue by etattershall** [etattershall/internet-of-thingies#1]
Will need to wait until we get the SD cards. Also, what operating system do we want to use?

**Comment by cal-id** [comment]
I guess start with raspbian (more documentation?).

https://www.raspberrypi.org/downloads/
These seem to be the ones that aren't specific systems (media centres / weather / classroom)

https://ubuntu-mate.org/raspberry-pi/
https://developer.ubuntu.com/core/get-started#snappy-raspi2
https://developer.microsoft.com/en-us/windows/iot/Downloads.htm    - not sure if free?
https://www.riscosopen.org/content/downloads/raspberry-pi

**Comment by cal-id** [comment]
Have brought in an SD card for initial testing.

You're welcome to grab the download from my PC (~1.5G) with a USB at some point if it saves time.
